[2023-02-20T05:36:12.315+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: predictit_dag.is_api_available scheduled__2023-02-18T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-02-20T05:36:12.316+0000] {local_task_job.py:147} INFO - Task is not able to be run
