[2023-02-20T05:38:02.258+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T05:38:00.897494+00:00 [queued]>
[2023-02-20T05:38:02.265+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T05:38:00.897494+00:00 [queued]>
[2023-02-20T05:38:02.265+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T05:38:02.266+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-20T05:38:02.266+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T05:38:02.276+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-02-20 05:38:00.897494+00:00
[2023-02-20T05:38:02.280+0000] {standard_task_runner.py:55} INFO - Started process 594 to run task
[2023-02-20T05:38:02.282+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'predictit_dag', 'is_api_available', 'manual__2023-02-20T05:38:00.897494+00:00', '--job-id', '542', '--raw', '--subdir', 'DAGS_FOLDER/predictit_dag.py', '--cfg-path', '/tmp/tmpmyuzhynm']
[2023-02-20T05:38:02.283+0000] {standard_task_runner.py:83} INFO - Job 542: Subtask is_api_available
[2023-02-20T05:38:02.321+0000] {task_command.py:388} INFO - Running <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T05:38:00.897494+00:00 [running]> on host 9e0dc30811b3
[2023-02-20T05:38:02.365+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=kyunlee@yahoo.com
AIRFLOW_CTX_DAG_OWNER=kyun
AIRFLOW_CTX_DAG_ID=predictit_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T05:38:00.897494+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T05:38:00.897494+00:00
[2023-02-20T05:38:02.366+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:38:02.372+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:38:02.694+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:38:02.695+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:39:02.756+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:39:02.760+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:39:03.072+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:39:03.072+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:40:03.128+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:40:03.133+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:40:03.287+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:40:03.287+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:41:03.323+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:41:03.328+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:41:03.484+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:41:03.484+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:42:03.546+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:42:03.551+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:42:03.837+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:42:03.837+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:43:03.892+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:43:03.897+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:43:04.204+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:43:04.204+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:44:04.264+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:44:04.270+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:44:04.560+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:44:04.560+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:45:04.617+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:45:04.622+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:45:04.937+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:45:04.938+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:46:04.996+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:46:05.001+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:46:05.309+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:46:05.310+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:47:05.346+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:47:05.351+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:47:05.652+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:47:05.652+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:48:05.706+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:48:05.711+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:48:06.017+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:48:06.018+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:49:06.054+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:49:06.059+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:49:06.224+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:49:06.225+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:50:06.286+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:50:06.291+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:50:06.595+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:50:06.596+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:51:06.649+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:51:06.654+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:51:06.807+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:51:06.807+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:52:06.866+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:52:06.871+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:52:07.042+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:52:07.043+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:53:07.096+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:53:07.101+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:53:07.412+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:53:07.412+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:54:07.433+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:54:07.438+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:54:07.754+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:54:07.754+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:55:07.815+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:55:07.820+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:55:08.145+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:55:08.145+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T05:56:08.206+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:56:08.260+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:56:08.575+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:56:08.575+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T05:57:08.602+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:57:08.607+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:57:08.930+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:57:08.930+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T05:58:08.966+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:58:08.972+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:58:09.260+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:58:09.261+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T05:59:09.264+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:59:09.270+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:59:09.575+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:59:09.576+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:00:09.636+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:00:09.641+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:00:09.990+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:00:09.990+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:01:10.007+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:01:10.011+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:01:10.380+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:01:10.380+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:02:10.437+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:02:10.443+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:02:10.757+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:02:10.758+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:03:10.819+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:03:10.824+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:03:11.160+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:03:11.160+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:04:11.216+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:04:11.221+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:04:11.424+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:04:11.425+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:05:11.466+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:05:11.471+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:05:11.650+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:05:11.651+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:06:11.712+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:06:11.717+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:06:12.018+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:06:12.019+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:07:12.076+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:07:12.081+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:07:12.391+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:07:12.392+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:08:12.396+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:08:12.401+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:08:12.720+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:08:12.721+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:09:12.776+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:09:12.781+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:09:12.961+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:09:12.961+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:10:12.966+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:10:12.971+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:10:13.304+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:10:13.304+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:11:13.366+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:11:13.370+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:11:13.675+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:11:13.675+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:12:13.687+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:12:13.693+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:12:14.023+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:12:14.023+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:13:14.076+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:13:14.082+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:13:14.385+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:13:14.385+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:14:14.446+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:14:14.451+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:14:14.797+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:14:14.797+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:15:14.856+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:15:14.869+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:15:15.054+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:15:15.054+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:16:15.116+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:16:15.121+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:16:15.448+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:16:15.448+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:17:15.507+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:17:15.512+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:17:15.830+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:17:15.830+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:18:15.890+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:18:15.895+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:18:16.063+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:18:16.063+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:19:16.118+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:19:16.124+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:19:16.280+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:19:16.280+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:20:16.340+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:20:16.345+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:20:16.664+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:20:16.664+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:21:16.725+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:21:16.730+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:21:17.077+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:21:17.077+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:22:17.097+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:22:17.102+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:22:17.278+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:22:17.278+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:23:17.336+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:23:17.341+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:23:17.657+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:23:17.658+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:24:17.716+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:24:17.722+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:24:17.907+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:24:17.907+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:25:17.969+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:25:17.974+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:25:18.293+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:25:18.293+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:26:18.346+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:26:18.351+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:26:18.650+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:26:18.651+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:27:18.706+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:27:18.711+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:27:19.026+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:27:19.026+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:28:19.078+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:28:19.083+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:28:19.251+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:28:19.251+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:29:19.306+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:29:19.311+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:29:19.633+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:29:19.633+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:30:19.634+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:30:19.640+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:30:19.970+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:30:19.970+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:31:20.026+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:31:20.031+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:31:20.365+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:31:20.366+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:32:20.426+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:32:20.431+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:32:20.732+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:32:20.732+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:33:20.792+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:33:20.797+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:33:21.099+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:33:21.099+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:34:21.161+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:34:21.166+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:34:21.479+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:34:21.479+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:35:21.539+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:35:21.545+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:35:21.719+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:35:21.720+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:36:21.776+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:36:21.781+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:36:21.938+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:36:21.938+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:37:21.997+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:37:22.002+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:37:22.298+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:37:22.298+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:38:22.356+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:38:22.361+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:38:22.661+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:38:22.662+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:39:22.716+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:39:22.721+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:39:23.042+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:39:23.043+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:40:23.096+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:40:23.102+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:40:23.422+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:40:23.422+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:41:23.482+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:41:23.487+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:41:23.797+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:41:23.797+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:42:23.856+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:42:23.899+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:42:24.218+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:42:24.218+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:43:24.267+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:43:24.272+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:43:24.618+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:43:24.618+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:44:24.676+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:44:24.681+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:44:25.023+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:44:25.024+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:45:25.079+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:45:25.084+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:45:25.399+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:45:25.399+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:46:25.436+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:46:25.441+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:46:25.631+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:46:25.631+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:47:25.690+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:47:25.695+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:47:25.870+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:47:25.871+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:48:25.916+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:48:25.921+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:48:26.229+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:48:26.229+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:49:26.279+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:49:26.284+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:49:26.608+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:49:26.608+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:50:26.633+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:50:26.638+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:50:27.101+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:50:27.101+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:51:27.156+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:51:27.161+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:51:27.490+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:51:27.490+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:52:27.551+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:52:27.556+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:52:27.722+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:52:27.722+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:53:27.767+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:53:27.772+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:53:28.087+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:53:28.087+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:54:28.146+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:54:28.151+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:54:28.470+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:54:28.470+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:55:28.478+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:55:28.484+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:55:28.786+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:55:28.787+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:56:28.829+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:56:28.835+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:56:29.156+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:56:29.156+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:57:29.198+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:57:29.203+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:57:29.525+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:57:29.526+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:58:29.572+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:58:29.577+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:58:29.892+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:58:29.893+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:59:29.954+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:59:29.960+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:59:30.318+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:59:30.319+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:00:30.380+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:00:30.385+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:00:30.904+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:00:30.904+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:01:30.957+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:01:30.962+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:01:31.292+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:01:31.293+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:02:31.346+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:02:31.351+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:02:31.561+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:02:31.561+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:03:31.616+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:03:31.621+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:03:31.939+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:03:31.939+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:04:31.996+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:04:32.001+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:04:32.170+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:04:32.170+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:05:32.229+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:05:32.234+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:05:32.583+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:05:32.583+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:06:32.630+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:06:32.635+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:06:33.068+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:06:33.069+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:07:33.126+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:07:33.131+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:07:33.456+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:07:33.456+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:08:33.515+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:08:33.521+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:08:33.861+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:08:33.861+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:09:33.923+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:09:33.929+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:09:34.248+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:09:34.249+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:10:34.289+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:10:34.295+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:10:34.648+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:10:34.648+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:11:34.684+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:11:34.689+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:11:35.013+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:11:35.014+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:12:35.071+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:12:35.077+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:12:35.403+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:12:35.404+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:13:35.459+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:13:35.465+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:13:35.812+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:13:35.812+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:14:35.821+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:14:35.827+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:14:36.151+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:14:36.152+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:15:36.206+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:15:36.212+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:15:36.531+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:15:36.531+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:16:36.591+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:16:36.596+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:16:36.919+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:16:36.919+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:17:36.976+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:17:36.981+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:17:37.342+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:17:37.342+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:18:37.396+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:18:37.401+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:18:37.710+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:18:37.710+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:19:37.736+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:19:37.741+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:19:38.045+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:19:38.046+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:20:38.106+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:20:38.111+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:20:38.274+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:20:38.275+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:21:38.310+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:21:38.315+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:21:38.623+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:21:38.624+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:22:38.666+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:22:38.672+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:22:38.991+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:22:38.991+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:23:39.023+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:23:39.029+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:23:39.358+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:23:39.358+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:24:39.388+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:24:39.394+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:24:39.712+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:24:39.712+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:25:39.766+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:25:39.771+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:25:40.111+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:25:40.112+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:26:40.173+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:26:40.179+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:26:40.501+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:26:40.501+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:27:40.563+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:27:40.569+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:27:40.886+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:27:40.886+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:28:40.904+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:28:40.909+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:28:41.237+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:28:41.238+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:29:41.285+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:29:41.319+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:29:41.641+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:29:41.642+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:30:41.650+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:30:41.655+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:30:41.825+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:30:41.826+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:31:41.886+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:31:41.891+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:31:42.063+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:31:42.063+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:32:42.106+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:32:42.111+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:32:42.423+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:32:42.424+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:33:42.452+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:33:42.457+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:33:42.759+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:33:42.759+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:34:42.816+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:34:42.821+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:34:43.132+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:34:43.132+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:35:43.191+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:35:43.196+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:35:43.528+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:35:43.528+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:36:43.586+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:36:43.599+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:36:43.781+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:36:43.782+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:37:43.830+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:37:43.836+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:37:44.175+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:37:44.176+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:38:44.237+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:38:44.243+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:38:44.412+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:38:44.413+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:39:44.474+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:39:44.480+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:39:44.654+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:39:44.654+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:40:44.657+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:40:44.662+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:40:44.989+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:40:44.989+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:41:45.026+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:41:45.031+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:41:45.206+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:41:45.206+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:42:45.266+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:42:45.272+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:42:45.596+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:42:45.597+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:43:45.631+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:43:45.636+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:43:45.942+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:43:45.942+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:44:45.970+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:44:45.975+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:44:46.143+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:44:46.143+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:45:46.199+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:45:46.204+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:45:46.410+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:45:46.410+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:46:46.471+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:46:46.477+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:46:46.786+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:46:46.787+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:47:46.845+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:47:46.850+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:47:47.017+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:47:47.017+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:48:47.076+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:48:47.081+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:48:47.400+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:48:47.401+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:49:47.404+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:49:47.409+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:49:47.713+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:49:47.713+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:50:47.766+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:50:47.771+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:50:48.079+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:50:48.080+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:51:48.137+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:51:48.142+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:51:48.316+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:51:48.316+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:52:48.376+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:52:48.381+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:52:48.694+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:52:48.694+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:53:48.741+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:53:48.746+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:53:49.055+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:53:49.055+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:54:49.116+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:54:49.121+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:54:49.430+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:54:49.430+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:55:49.442+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:55:49.447+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:55:49.773+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:55:49.773+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:56:49.829+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:56:49.834+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:56:50.143+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:56:50.143+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:57:50.183+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:57:50.189+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:57:50.485+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:57:50.485+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:58:50.490+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:58:50.495+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:58:50.800+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:58:50.801+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:59:50.829+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:59:50.834+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:59:51.001+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:59:51.001+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:00:51.056+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:00:51.061+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:00:51.367+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:00:51.367+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:01:51.425+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:01:51.431+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:01:51.758+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:01:51.759+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:02:51.814+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:02:51.820+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:02:52.139+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:02:52.139+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:03:52.196+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:03:52.201+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:03:52.518+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:03:52.519+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:04:52.571+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:04:52.577+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:04:52.876+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:04:52.876+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:05:52.936+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:05:52.941+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:05:53.285+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:05:53.285+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:06:53.319+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:06:53.325+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:06:53.632+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:06:53.632+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:07:53.692+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:07:53.698+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:07:54.002+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:07:54.003+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:08:54.064+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:08:54.070+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:08:54.379+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:08:54.379+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:09:54.434+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:09:54.440+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:09:54.747+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:09:54.747+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:10:54.806+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:10:54.811+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:10:55.120+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:10:55.120+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:11:55.171+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:11:55.176+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:11:55.480+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:11:55.480+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:12:55.537+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:12:55.542+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:12:55.750+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:12:55.751+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:13:55.806+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:13:55.811+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:13:56.152+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:13:56.153+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:14:56.206+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:14:56.211+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:14:56.525+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:14:56.526+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:15:56.557+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:15:56.562+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:15:56.883+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:15:56.883+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:16:56.936+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:16:56.941+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:16:57.250+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:16:57.250+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:17:57.259+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:17:57.264+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:17:57.594+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:17:57.594+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:18:57.639+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:18:57.646+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:18:57.980+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:18:57.981+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:19:58.043+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:19:58.048+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:19:58.366+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:19:58.367+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:20:58.428+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:20:58.433+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:20:58.742+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:20:58.743+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:21:58.765+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:21:58.771+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:21:59.098+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:21:59.098+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:22:59.130+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:22:59.136+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:22:59.474+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:22:59.474+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:23:59.514+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:23:59.520+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:23:59.827+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:23:59.828+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:24:59.874+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:24:59.880+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:25:00.230+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:25:00.230+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:26:00.286+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:26:00.294+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:26:00.608+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:26:00.609+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:27:00.670+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:27:00.677+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:27:00.874+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:27:00.874+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:28:00.931+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:28:00.937+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:28:01.242+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:28:01.242+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:29:01.296+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:29:01.303+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:29:01.615+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:29:01.616+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:30:01.667+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:30:01.673+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:30:01.994+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:30:01.994+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:31:02.046+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:31:02.130+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:31:02.462+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:31:02.462+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:32:02.516+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:32:02.522+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:32:02.842+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:32:02.842+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:33:02.902+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:33:02.908+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:33:03.082+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:33:03.083+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:34:03.136+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:34:03.151+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:34:03.326+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:34:03.327+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:35:03.386+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:35:03.393+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:35:03.699+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:35:03.700+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:36:03.762+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:36:03.768+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:36:04.125+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:36:04.125+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:37:04.187+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:37:04.193+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:37:04.500+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:37:04.500+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:38:04.555+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:38:04.561+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:38:04.880+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:38:04.880+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:39:04.923+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:39:04.930+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:39:05.095+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:39:05.095+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:40:05.156+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:40:05.162+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:40:05.463+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:40:05.464+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:41:05.516+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:41:05.522+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:41:05.835+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:41:05.835+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:42:05.896+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:42:05.901+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:42:06.205+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:42:06.205+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:43:06.255+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:43:06.261+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:43:06.560+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:43:06.560+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:44:06.615+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:44:06.621+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:44:06.791+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:44:06.791+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:45:06.845+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:45:06.852+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:45:07.160+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:45:07.160+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:46:07.216+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:46:07.222+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:46:07.544+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:46:07.544+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:47:07.582+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:47:07.588+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:47:07.900+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:47:07.901+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:48:07.959+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:48:07.965+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:48:08.136+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:48:08.136+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:49:08.198+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:49:08.205+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:49:08.572+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:49:08.573+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:50:08.626+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:50:08.632+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:50:08.945+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:50:08.945+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:51:09.006+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:51:09.012+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:51:09.317+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:51:09.318+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:52:09.376+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:52:09.382+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:52:09.702+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:52:09.702+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:53:09.756+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:53:09.799+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:53:10.100+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:53:10.100+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:54:10.158+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:54:10.165+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:54:10.479+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:54:10.480+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:55:10.506+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:55:10.512+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:55:10.690+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:55:10.690+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:56:10.746+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:56:10.752+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:56:10.927+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:56:10.927+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:57:10.958+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:57:10.964+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:57:11.278+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:57:11.278+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:58:11.317+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:58:11.322+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:58:11.644+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:58:11.644+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:59:11.701+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:59:11.707+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:59:12.015+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:59:12.016+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:00:12.048+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:00:12.054+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:00:12.376+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:00:12.377+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:01:12.436+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:01:12.441+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:01:12.756+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:01:12.757+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:02:12.786+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:02:12.793+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:02:13.087+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:02:13.088+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:03:13.146+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:03:13.154+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:03:13.456+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:03:13.457+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:04:13.517+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:04:13.523+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:04:13.690+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:04:13.691+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:05:13.694+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:05:13.700+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:05:14.020+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:05:14.020+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:06:14.075+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:06:14.081+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:06:14.403+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:06:14.404+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:07:14.466+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:07:14.472+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:07:14.799+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:07:14.799+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:08:14.856+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:08:14.862+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:08:15.180+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:08:15.180+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:09:15.242+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:09:15.249+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:09:15.570+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:09:15.570+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:10:15.626+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:10:15.632+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:10:15.940+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:10:15.940+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:11:15.998+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:11:16.011+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:11:16.328+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:11:16.329+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:12:16.345+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:12:16.352+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:12:16.661+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:12:16.662+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:13:16.716+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:13:16.723+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:13:16.900+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:13:16.901+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:14:16.956+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:14:16.961+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:14:17.132+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:14:17.133+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:15:17.171+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:15:17.178+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:15:17.353+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:15:17.354+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:16:17.366+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:16:17.372+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:16:17.691+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:16:17.691+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:17:17.700+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:17:17.708+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:17:18.022+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:17:18.022+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:18:18.039+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:18:18.046+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:18:18.259+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:18:18.260+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:19:18.281+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:19:18.288+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:19:18.604+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:19:18.604+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:20:18.644+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:20:18.650+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:20:18.814+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:20:18.814+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:21:18.819+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:21:18.825+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:21:19.167+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:21:19.167+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:22:19.228+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:22:19.235+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:22:19.550+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:22:19.550+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:23:19.612+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:23:19.619+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:23:19.936+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:23:19.936+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:24:19.966+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:24:19.973+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:24:20.154+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:24:20.155+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:25:20.215+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:25:20.222+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:25:20.530+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:25:20.530+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:26:20.582+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:26:20.588+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:26:20.909+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:26:20.909+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:27:20.945+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:27:20.951+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:27:21.262+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:27:21.262+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:28:21.323+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:28:21.328+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:28:21.639+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:28:21.640+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:29:21.656+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:29:21.662+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:29:21.968+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:29:21.969+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:30:22.026+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:30:22.031+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:30:22.342+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:30:22.342+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:31:22.401+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:31:22.407+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:31:22.762+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:31:22.763+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:32:22.799+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:32:22.806+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:32:23.130+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:32:23.130+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:33:23.186+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:33:23.192+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:33:24.407+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:33:24.408+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:34:24.464+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:34:24.470+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:34:24.769+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:34:24.769+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:35:24.826+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:35:24.832+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:35:25.402+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:35:25.402+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:36:25.438+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:36:25.444+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:36:25.759+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:36:25.760+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:37:25.814+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:37:25.820+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:37:25.997+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:37:25.997+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:38:26.044+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:38:26.050+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:38:26.395+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:38:26.395+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:39:26.455+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:39:26.462+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:39:26.783+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:39:26.783+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:40:26.839+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:40:26.845+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:40:27.202+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:40:27.202+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:41:27.262+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:41:27.269+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:41:27.575+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:41:27.576+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:42:27.635+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:42:27.642+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:42:27.966+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:42:27.966+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:43:28.017+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:43:28.023+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:43:28.343+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:43:28.344+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:44:28.396+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:44:28.401+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:44:28.712+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:44:28.713+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:45:28.766+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:45:28.772+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:45:29.073+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:45:29.073+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:46:29.131+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:46:29.137+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:46:29.455+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:46:29.455+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:47:29.515+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:47:29.522+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:47:29.867+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:47:29.868+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:48:29.900+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:48:29.906+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:48:30.237+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:48:30.238+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:49:30.278+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:49:30.284+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:49:30.601+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:49:30.602+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:50:30.656+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:50:30.661+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:50:31.014+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:50:31.014+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:51:31.072+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:51:31.078+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:51:31.435+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:51:31.435+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:52:31.462+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:52:31.468+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:52:31.785+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:52:31.786+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:53:31.805+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:53:31.811+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:53:32.147+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:53:32.147+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:54:32.191+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:54:32.197+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:54:32.370+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:54:32.371+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:55:32.426+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:55:32.432+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:55:32.746+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:55:32.746+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:56:32.807+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:56:32.813+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:56:33.129+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:56:33.129+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:57:33.166+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:57:33.171+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:57:33.339+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:57:33.340+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:58:33.395+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:58:33.401+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:58:33.716+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:58:33.716+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:59:33.778+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:59:33.785+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:59:34.096+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:59:34.096+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:00:34.158+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:00:34.164+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:00:34.461+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:00:34.461+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:01:34.488+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:01:34.495+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:01:34.801+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:01:34.802+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:02:34.807+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:02:34.814+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:02:35.134+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:02:35.134+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:03:35.195+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:03:35.202+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:03:35.382+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:03:35.382+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:04:35.443+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:04:35.449+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:04:35.763+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:04:35.763+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:05:35.815+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:05:35.822+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:05:36.143+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:05:36.143+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:06:36.195+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:06:36.202+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:06:36.818+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:06:36.818+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:07:36.876+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:07:36.882+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:07:37.206+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:07:37.207+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:08:37.268+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:08:37.275+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:08:37.590+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:08:37.591+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:09:37.644+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:09:37.650+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:09:37.975+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:09:37.976+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:10:38.037+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:10:38.044+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:10:38.227+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:10:38.227+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:11:38.286+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:11:38.292+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:11:38.459+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:11:38.459+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:12:38.508+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:12:38.515+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:12:38.829+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:12:38.829+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:13:38.886+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:13:38.892+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:13:39.063+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:13:39.063+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:14:39.119+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:14:39.126+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:14:39.479+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:14:39.480+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:15:39.530+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:15:39.535+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:15:39.702+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:15:39.703+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:16:39.763+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:16:39.769+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:16:40.086+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:16:40.086+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:17:40.145+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:17:40.151+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:17:40.476+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:17:40.476+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:18:40.508+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:18:40.513+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:18:40.832+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:18:40.832+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:19:40.874+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:19:40.879+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:19:41.188+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:19:41.188+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:20:41.221+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:20:41.226+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:20:41.532+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:20:41.532+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:21:41.568+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:21:41.574+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:21:41.879+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:21:41.879+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:22:41.931+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:22:41.937+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:22:42.255+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:22:42.255+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:23:42.315+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:23:42.322+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:23:42.624+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:23:42.624+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:24:42.686+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:24:42.692+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:24:42.879+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:24:42.879+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:25:42.940+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:25:42.947+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:25:43.255+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:25:43.255+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:26:43.317+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:26:43.322+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:26:43.636+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:26:43.637+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:27:43.695+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:27:43.701+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:27:44.001+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:27:44.001+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:28:44.064+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:28:44.069+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:28:44.416+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:28:44.417+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:29:44.478+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:29:44.485+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:29:44.794+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:29:44.794+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:30:44.855+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:30:44.861+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:30:45.186+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:30:45.186+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:31:45.215+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:31:45.221+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:31:45.537+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:31:45.537+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:32:45.549+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:32:45.555+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:32:45.857+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:32:45.858+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:33:45.865+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:33:45.872+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:33:46.221+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:33:46.222+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:34:46.275+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:34:46.281+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:34:46.579+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:34:46.580+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:35:46.636+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:35:46.641+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:35:46.962+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:35:46.962+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:36:47.023+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:36:47.029+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:36:47.347+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:36:47.348+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:37:47.409+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:37:47.416+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:37:47.762+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:37:47.762+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:38:47.802+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:38:47.810+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:38:47.973+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:38:47.974+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:39:48.027+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:39:48.033+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:39:48.337+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:39:48.338+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:40:48.399+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:40:48.405+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:40:48.713+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:40:48.714+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:41:48.723+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:41:48.729+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:41:49.056+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:41:49.056+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:42:49.115+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:42:49.121+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:42:49.435+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:42:49.435+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:43:49.496+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:43:49.501+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:43:49.822+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:43:49.823+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:44:49.875+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:44:49.881+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:44:50.191+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:44:50.192+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:45:50.231+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:45:50.238+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:45:50.557+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:45:50.557+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:46:50.610+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:46:50.616+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:46:50.932+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:46:50.932+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:47:50.948+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:47:50.953+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:47:51.259+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:47:51.259+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:48:51.263+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:48:51.268+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:48:51.464+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:48:51.464+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:49:51.526+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:49:51.531+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:49:51.834+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:49:51.834+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:50:51.860+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:50:51.866+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:50:52.501+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:50:52.501+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:51:52.542+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:51:52.548+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:51:52.728+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:51:52.728+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:52:52.768+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:52:52.774+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:52:53.096+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:52:53.096+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:53:53.151+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:53:53.157+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:53:53.473+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:53:53.473+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:54:53.493+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:54:53.499+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:54:53.819+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:54:53.820+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:55:53.875+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:55:53.882+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:55:54.184+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:55:54.185+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:56:54.245+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:56:54.252+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:56:54.426+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:56:54.426+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:57:54.440+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:57:54.447+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:57:54.759+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:57:54.759+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:58:54.820+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:58:54.827+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:58:55.153+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:58:55.153+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:59:55.209+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:59:55.215+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:59:55.567+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:59:55.567+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:00:55.627+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:00:55.634+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:00:55.945+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:00:55.945+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:01:56.005+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:01:56.012+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:01:56.303+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:01:56.303+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:02:56.365+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:02:56.371+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:02:56.690+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:02:56.691+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:03:56.745+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:03:56.751+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:03:57.045+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:03:57.045+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:04:57.105+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:04:57.111+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:04:57.277+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:04:57.277+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:05:57.335+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:05:57.341+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:05:57.644+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:05:57.645+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:06:57.686+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:06:57.693+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:06:57.999+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:06:57.999+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:07:58.055+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:07:58.061+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:07:58.384+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:07:58.385+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:08:58.435+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:08:58.442+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:08:58.770+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:08:58.770+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:09:58.826+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:09:58.833+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:09:59.153+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:09:59.154+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:10:59.186+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:10:59.192+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:10:59.503+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:10:59.503+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:11:59.555+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:11:59.563+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:11:59.880+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:11:59.880+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:12:59.942+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:12:59.948+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:13:00.265+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:13:00.265+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:14:00.327+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:14:00.333+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:14:00.657+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:14:00.658+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:15:00.710+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:15:00.716+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:15:00.882+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:15:00.883+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:16:00.944+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:16:00.949+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:16:01.256+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:16:01.257+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:17:01.318+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:17:01.324+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:17:01.681+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:17:01.682+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:18:01.744+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:18:01.749+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:18:01.919+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:18:01.919+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:19:01.975+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:19:01.981+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:19:02.306+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:19:02.306+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:20:02.318+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:20:02.325+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:20:02.652+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:20:02.652+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:21:02.659+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:21:02.665+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:21:02.971+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:21:02.971+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:22:03.025+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:22:03.032+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:22:03.353+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:22:03.353+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:23:03.390+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:23:03.398+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:23:03.579+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:23:03.580+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:24:03.616+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:24:03.622+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:24:03.954+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:24:03.955+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:25:04.015+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:25:04.020+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:25:04.339+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:25:04.340+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:26:04.386+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:26:04.392+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:26:04.707+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:26:04.708+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:27:04.765+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:27:04.771+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:27:05.082+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:27:05.083+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:28:05.143+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:28:05.150+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:28:05.475+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:28:05.475+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:29:05.506+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:29:05.512+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:29:05.681+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:29:05.682+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:30:05.735+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:30:05.740+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:30:06.056+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:30:06.056+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T15:35:17.046+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T05:38:00.897494+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-02-20T15:35:17.052+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T05:38:00.897494+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-02-20T15:35:17.053+0000] {local_task_job.py:147} INFO - Task is not able to be run
