[2023-02-20T04:57:39.776+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T04:57:38.270656+00:00 [queued]>
[2023-02-20T04:57:39.783+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T04:57:38.270656+00:00 [queued]>
[2023-02-20T04:57:39.783+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T04:57:39.784+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-20T04:57:39.784+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T04:57:39.792+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-02-20 04:57:38.270656+00:00
[2023-02-20T04:57:39.795+0000] {standard_task_runner.py:55} INFO - Started process 27953 to run task
[2023-02-20T04:57:39.796+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'predictit_dag', 'is_api_available', 'manual__2023-02-20T04:57:38.270656+00:00', '--job-id', '540', '--raw', '--subdir', 'DAGS_FOLDER/predictit_dag.py', '--cfg-path', '/tmp/tmpcnbwstvb']
[2023-02-20T04:57:39.797+0000] {standard_task_runner.py:83} INFO - Job 540: Subtask is_api_available
[2023-02-20T04:57:39.826+0000] {task_command.py:388} INFO - Running <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T04:57:38.270656+00:00 [running]> on host 9e0dc30811b3
[2023-02-20T04:57:39.865+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=kyunlee@yahoo.com
AIRFLOW_CTX_DAG_OWNER=kyun
AIRFLOW_CTX_DAG_ID=predictit_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T04:57:38.270656+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T04:57:38.270656+00:00
[2023-02-20T04:57:39.865+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T04:57:39.870+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T04:57:40.243+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T04:57:40.243+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T04:58:40.305+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T04:58:40.311+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T04:58:40.635+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T04:58:40.635+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T04:59:40.696+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T04:59:40.701+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T04:59:41.014+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T04:59:41.014+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:00:41.067+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:00:41.073+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:00:41.390+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:00:41.390+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:01:41.446+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:01:41.451+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:01:41.783+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:01:41.784+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:02:41.836+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:02:41.841+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:02:42.040+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:02:42.040+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:03:42.102+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:03:42.107+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:03:42.447+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:03:42.447+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:04:42.506+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:04:42.510+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:04:42.807+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:04:42.808+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:05:42.866+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:05:42.871+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:05:43.167+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:05:43.168+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:06:43.226+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:06:43.231+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:06:43.543+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:06:43.543+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:07:43.550+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:07:43.555+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:07:43.883+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:07:43.883+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:08:43.908+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:08:43.913+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:08:44.221+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:08:44.221+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:09:44.262+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:09:44.267+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:09:44.579+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:09:44.579+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:10:44.606+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:10:44.611+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:10:44.922+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:10:44.923+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:11:44.976+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:11:44.981+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:11:45.293+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:11:45.294+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:12:45.347+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:12:45.352+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:12:45.688+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:12:45.689+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:13:45.747+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:13:45.752+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:13:46.066+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:13:46.067+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:14:46.126+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:14:46.131+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:14:46.443+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:14:46.443+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:15:46.452+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:15:46.457+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:15:46.643+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:15:46.644+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:16:46.696+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:16:46.701+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:16:47.020+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:16:47.021+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:17:47.082+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:17:47.087+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:17:47.273+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:17:47.273+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:18:47.326+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:18:47.332+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:18:47.658+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:18:47.658+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:19:47.716+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:19:47.722+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:19:48.046+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:19:48.047+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:20:48.106+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:20:48.111+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:20:48.416+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:20:48.416+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:21:48.448+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:21:48.454+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:21:48.764+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:21:48.764+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:22:48.811+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:22:48.816+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:22:49.359+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:22:49.360+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:23:49.416+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:23:49.421+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:23:49.728+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:23:49.728+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:24:49.786+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:24:49.791+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:24:50.104+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:24:50.104+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:25:50.146+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:25:50.152+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:25:50.486+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:25:50.487+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:26:50.491+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:26:50.497+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:26:50.816+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:26:50.816+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:27:50.878+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:27:50.883+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:27:51.080+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:27:51.080+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:28:51.142+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:28:51.147+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:28:51.330+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:28:51.330+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:29:51.391+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:29:51.397+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:29:51.715+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:29:51.715+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:30:51.777+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:30:51.782+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:30:52.104+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:30:52.104+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:31:52.146+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:31:52.153+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:31:52.463+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:31:52.463+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:32:52.522+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:32:52.528+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:32:52.857+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:32:52.858+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:33:52.908+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:33:52.913+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:33:53.232+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:33:53.233+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:34:53.294+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:34:53.300+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:34:53.468+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:34:53.468+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:35:53.509+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:35:53.515+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:35:53.830+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:35:53.830+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:36:53.886+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:36:53.891+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:36:54.207+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:36:54.207+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/api/'."
}
[2023-02-20T05:37:54.269+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:37:54.274+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:37:54.462+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:37:54.463+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:38:54.465+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:38:54.470+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:38:54.624+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:38:54.625+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:39:54.645+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:39:54.651+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:39:54.958+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:39:54.958+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:40:55.006+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:40:55.012+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:40:55.327+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:40:55.328+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:41:55.386+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:41:55.391+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:41:55.696+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:41:55.697+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:42:55.708+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:42:55.713+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:42:56.042+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:42:56.042+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:43:56.067+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:43:56.072+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:43:56.382+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:43:56.382+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:44:56.436+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:44:56.441+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:44:56.613+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:44:56.613+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:45:56.667+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:45:56.672+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:45:56.973+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:45:56.974+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:46:57.029+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:46:57.034+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:46:57.331+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:46:57.331+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:47:57.386+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:47:57.391+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:47:57.600+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:47:57.600+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:48:57.656+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:48:57.662+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:48:57.967+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:48:57.967+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:49:57.972+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:49:57.977+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:49:58.142+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:49:58.142+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:50:58.172+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:50:58.177+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:50:58.326+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:50:58.326+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:51:58.386+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:51:58.391+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:51:58.693+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:51:58.694+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:52:58.698+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:52:58.703+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:52:58.900+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:52:58.900+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:53:58.960+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:53:58.967+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:53:59.274+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:53:59.275+0000] {http.py:164} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

[2023-02-20T05:54:59.330+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:54:59.335+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:54:59.656+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:54:59.657+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T05:55:59.717+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:55:59.723+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:55:59.900+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:55:59.901+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T05:56:59.955+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:56:59.960+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:57:00.278+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:57:00.279+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T05:58:00.289+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:58:00.294+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:58:00.486+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:58:00.487+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T05:59:00.548+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T05:59:00.553+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T05:59:00.860+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T05:59:00.860+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:00:00.916+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:00:00.921+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:00:01.282+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:00:01.282+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:01:01.339+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:01:01.343+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:01:01.647+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:01:01.648+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:02:01.695+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:02:01.700+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:02:01.851+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:02:01.851+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:03:01.909+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:03:01.914+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:03:02.099+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:03:02.099+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:04:02.160+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:04:02.165+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:04:02.458+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:04:02.458+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:05:02.519+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:05:02.525+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:05:02.861+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:05:02.862+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:06:02.874+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:06:02.879+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:06:03.203+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:06:03.204+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:07:03.264+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:07:03.269+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:07:03.585+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:07:03.586+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:08:03.611+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:08:03.616+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:08:03.821+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:08:03.822+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:09:03.876+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:09:03.881+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:09:04.214+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:09:04.215+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:10:04.265+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:10:04.270+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:10:04.644+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:10:04.644+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:11:04.706+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:11:04.710+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:11:05.029+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:11:05.029+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:12:05.077+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:12:05.083+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:12:05.246+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:12:05.247+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:13:05.306+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:13:05.311+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:13:05.625+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:13:05.625+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:14:05.686+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:14:05.691+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:14:05.844+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:14:05.845+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:15:05.896+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:15:05.901+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:15:06.180+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:15:06.181+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:16:06.236+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:16:06.241+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:16:06.546+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:16:06.546+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:17:06.606+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:17:06.611+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:17:06.923+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:17:06.924+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:18:06.952+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:18:06.957+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:18:07.276+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:18:07.277+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:19:07.320+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:19:07.325+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:19:07.639+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:19:07.639+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:20:07.679+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:20:07.729+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:20:08.071+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:20:08.072+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:21:08.089+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:21:08.093+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:21:08.412+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:21:08.413+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:22:08.451+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:22:08.456+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:22:08.804+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:22:08.804+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:23:08.846+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:23:08.851+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:23:09.169+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:23:09.170+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:24:09.226+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:24:09.230+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:24:09.542+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:24:09.542+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:25:09.603+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:25:09.608+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:25:09.972+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:25:09.972+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:26:10.033+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:26:10.038+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:26:10.336+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:26:10.336+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:27:10.346+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:27:10.351+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:27:10.636+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:27:10.636+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:28:10.686+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:28:10.693+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:28:10.996+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:28:10.996+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:29:11.058+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:29:11.063+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:29:11.363+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:29:11.363+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:30:11.401+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:30:11.407+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:30:11.711+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:30:11.712+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:31:11.766+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:31:11.771+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:31:12.078+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:31:12.078+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:32:12.115+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:32:12.120+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:32:12.445+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:32:12.446+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:33:12.506+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:33:12.512+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:33:12.852+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:33:12.853+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:34:12.905+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:34:12.910+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:34:13.236+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:34:13.237+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:35:13.276+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:35:13.282+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:35:13.614+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:35:13.614+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:36:13.644+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:36:13.649+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:36:13.966+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:36:13.967+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:37:14.027+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:37:14.033+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:37:14.228+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:37:14.228+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:38:14.286+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:38:14.291+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:38:14.608+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:38:14.608+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:39:14.666+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:39:14.671+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:39:14.997+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:39:14.997+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:40:15.050+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:40:15.055+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:40:15.388+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:40:15.388+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:41:15.449+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:41:15.455+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:41:15.774+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:41:15.774+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:42:15.836+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:42:15.841+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:42:16.173+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:42:16.173+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:43:16.228+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:43:16.233+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:43:16.412+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:43:16.413+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:44:16.428+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:44:16.433+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:44:16.797+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:44:16.798+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:45:16.831+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:45:16.836+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:45:17.155+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:45:17.156+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:46:17.198+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:46:17.204+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:46:17.544+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:46:17.545+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:47:17.596+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:47:17.603+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:47:17.936+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:47:17.936+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:48:17.996+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:48:18.040+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:48:18.350+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:48:18.351+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:49:18.410+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:49:18.415+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:49:18.594+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:49:18.595+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:50:18.604+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:50:18.609+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:50:18.929+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:50:18.929+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:51:18.986+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:51:18.991+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:51:19.193+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:51:19.193+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:52:19.229+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:52:19.234+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:52:19.545+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:52:19.545+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:53:19.605+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:53:19.610+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:53:19.934+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:53:19.935+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:54:19.996+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:54:20.002+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:54:20.180+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:54:20.181+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:55:20.196+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:55:20.201+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:55:20.516+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:55:20.516+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:56:20.576+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:56:20.581+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:56:20.926+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:56:20.927+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:57:20.940+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:57:20.946+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:57:21.257+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:57:21.258+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:58:21.318+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:58:21.323+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:58:21.629+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:58:21.629+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T06:59:21.691+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T06:59:21.696+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T06:59:22.006+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T06:59:22.006+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:00:22.038+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:00:22.043+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:00:22.360+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:00:22.361+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:01:22.416+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:01:22.422+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:01:22.763+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:01:22.763+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:02:22.816+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:02:22.821+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:02:23.141+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:02:23.141+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:03:23.198+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:03:23.259+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:03:23.583+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:03:23.583+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:04:23.636+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:04:23.640+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:04:23.966+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:04:23.966+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:05:24.026+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:05:24.031+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:05:24.215+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:05:24.215+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:06:24.256+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:06:24.261+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:06:24.643+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:06:24.643+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:07:24.651+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:07:24.656+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:07:24.972+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:07:24.973+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:08:25.034+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:08:25.039+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:08:25.358+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:08:25.358+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:09:25.420+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:09:25.427+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:09:25.603+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:09:25.603+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:10:25.621+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:10:25.627+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:10:25.958+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:10:25.958+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:11:26.020+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:11:26.026+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:11:26.369+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:11:26.369+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:12:26.426+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:12:26.431+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:12:26.760+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:12:26.760+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:13:26.767+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:13:26.773+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:13:27.116+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:13:27.116+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:14:27.161+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:14:27.167+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:14:27.534+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:14:27.534+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:15:27.588+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:15:27.594+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:15:27.899+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:15:27.899+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:16:27.957+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:16:27.963+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:16:28.288+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:16:28.291+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:17:28.343+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:17:28.349+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:17:28.668+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:17:28.668+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:18:28.726+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:18:28.731+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:18:29.039+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:18:29.040+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:19:29.097+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:19:29.102+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:19:29.444+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:19:29.444+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:20:29.503+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:20:29.530+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:20:29.876+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:20:29.877+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:21:29.936+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:21:29.943+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:21:30.136+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:21:30.136+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:22:30.171+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:22:30.177+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:22:30.506+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:22:30.507+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:23:30.567+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:23:30.573+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:23:30.892+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:23:30.892+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:24:30.906+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:24:30.912+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:24:31.268+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:24:31.269+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:25:31.326+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:25:31.334+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:25:31.680+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:25:31.680+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:26:31.736+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:26:31.791+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:26:32.393+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:26:32.394+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:27:32.451+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:27:32.457+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:27:32.784+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:27:32.784+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:28:32.829+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:28:32.834+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:28:33.145+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:28:33.145+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:29:33.206+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:29:33.211+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:29:33.532+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:29:33.532+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:30:33.571+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:30:33.576+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:30:33.766+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:30:33.766+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:31:33.826+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:31:33.831+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:31:34.153+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:31:34.154+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:32:34.214+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:32:34.219+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:32:34.535+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:32:34.535+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:33:34.596+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:33:34.619+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:33:34.798+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:33:34.799+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:34:34.855+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:34:34.861+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:34:35.035+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:34:35.035+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:35:35.043+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:35:35.048+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:35:35.353+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:35:35.353+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:36:35.414+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:36:35.420+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:36:35.619+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:36:35.619+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:37:35.648+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:37:35.653+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:37:35.977+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:37:35.978+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:38:36.007+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:38:36.012+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:38:36.351+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:38:36.351+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:39:36.383+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:39:36.388+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:39:36.706+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:39:36.707+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:40:36.755+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:40:36.760+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:40:37.086+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:40:37.086+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:41:37.143+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:41:37.148+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:41:37.707+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:41:37.707+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:42:37.764+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:42:37.769+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:42:38.077+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:42:38.077+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:43:38.136+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:43:38.141+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:43:38.308+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:43:38.308+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:44:38.348+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:44:38.353+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:44:38.657+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:44:38.658+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:45:38.712+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:45:38.717+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:45:39.025+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:45:39.026+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:46:39.086+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:46:39.110+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:46:39.305+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:46:39.306+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:47:39.348+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:47:39.353+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:47:39.668+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:47:39.668+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:48:39.726+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:48:39.731+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:48:39.908+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:48:39.909+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:49:39.966+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:49:39.971+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:49:40.285+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:49:40.286+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:50:40.335+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:50:40.340+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:50:40.691+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:50:40.691+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:51:40.745+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:51:40.750+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:51:41.097+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:51:41.098+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:52:41.156+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:52:41.161+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:52:41.477+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:52:41.477+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:53:41.530+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:53:41.535+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:53:41.705+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:53:41.705+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:54:41.767+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:54:41.772+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:54:42.092+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:54:42.092+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:55:42.146+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:55:42.151+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:55:42.327+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:55:42.328+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:56:42.386+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:56:42.391+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:56:42.632+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:56:42.632+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:57:42.684+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:57:42.689+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:57:42.844+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:57:42.844+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:58:42.900+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:58:42.905+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:58:43.084+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:58:43.084+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T07:59:43.088+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T07:59:43.093+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T07:59:43.397+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T07:59:43.397+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:00:43.458+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:00:43.463+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:00:43.772+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:00:43.772+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:01:43.829+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:01:43.835+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:01:44.202+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:01:44.203+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:02:44.261+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:02:44.274+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:02:44.611+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:02:44.612+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:03:44.665+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:03:44.671+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:03:44.988+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:03:44.989+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:04:45.028+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:04:45.033+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:04:45.364+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:04:45.364+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:05:45.416+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:05:45.421+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:05:45.739+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:05:45.739+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:06:45.798+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:06:45.805+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:06:46.183+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:06:46.183+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:07:46.219+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:07:46.226+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:07:46.405+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:07:46.405+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:08:46.466+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:08:46.471+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:08:46.821+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:08:46.822+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:09:46.884+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:09:46.889+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:09:47.201+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:09:47.202+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:10:47.263+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:10:47.268+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:10:47.438+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:10:47.438+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:11:47.471+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:11:47.476+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:11:47.657+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:11:47.658+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:12:47.719+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:12:47.724+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:12:48.029+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:12:48.030+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:13:48.087+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:13:48.093+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:13:48.411+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:13:48.411+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:14:48.466+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:14:48.471+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:14:48.815+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:14:48.816+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:15:48.854+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:15:48.859+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:15:49.182+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:15:49.182+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:16:49.236+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:16:49.243+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:16:49.449+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:16:49.449+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:17:49.506+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:17:49.511+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:17:49.828+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:17:49.828+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:18:49.854+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:18:49.859+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:18:50.176+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:18:50.176+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:19:50.196+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:19:50.201+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:19:50.510+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:19:50.511+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:20:50.572+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:20:50.577+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:20:50.895+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:20:50.896+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:21:50.956+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:21:50.961+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:21:51.324+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:21:51.324+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:22:51.376+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:22:51.381+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:22:51.690+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:22:51.691+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:23:51.746+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:23:51.751+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:23:52.074+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:23:52.075+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:24:52.135+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:24:52.158+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:24:52.329+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:24:52.330+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:25:52.391+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:25:52.397+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:25:52.710+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:25:52.710+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:26:52.766+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:26:52.772+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:26:53.140+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:26:53.141+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:27:53.185+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:27:53.191+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:27:53.520+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:27:53.520+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:28:53.576+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:28:53.582+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:28:53.890+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:28:53.890+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:29:53.946+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:29:53.952+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:29:54.255+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:29:54.256+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:30:54.316+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:30:54.322+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:30:54.648+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:30:54.648+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:31:54.683+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:31:54.690+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:31:55.009+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:31:55.009+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:32:55.071+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:32:55.077+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:32:55.436+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:32:55.437+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:33:55.499+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:33:55.505+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:33:55.811+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:33:55.811+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:34:55.819+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:34:55.825+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:34:56.136+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:34:56.136+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:35:56.184+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:35:56.190+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:35:56.498+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:35:56.498+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:36:56.539+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:36:56.545+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:36:56.737+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:36:56.738+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:37:56.777+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:37:56.783+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:37:57.083+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:37:57.083+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:38:57.122+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:38:57.128+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:38:57.300+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:38:57.300+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:39:57.306+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:39:57.312+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:39:57.493+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:39:57.494+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:40:57.546+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:40:57.552+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:40:57.893+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:40:57.893+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:41:57.928+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:41:57.934+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:41:58.297+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:41:58.297+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:42:58.334+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:42:58.339+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:42:58.649+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:42:58.649+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:43:58.684+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:43:58.690+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:43:58.990+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:43:58.991+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:44:59.046+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:44:59.054+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:44:59.368+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:44:59.368+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:45:59.430+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:45:59.437+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:45:59.762+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:45:59.762+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:46:59.782+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:46:59.789+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:47:00.117+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:47:00.117+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:48:00.157+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:48:00.164+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:48:00.470+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:48:00.470+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:49:00.532+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:49:00.538+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:49:00.853+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:49:00.854+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:50:00.910+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:50:00.917+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:50:01.231+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:50:01.231+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:51:01.244+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:51:01.251+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:51:01.556+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:51:01.556+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:52:01.567+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:52:01.573+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:52:01.898+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:52:01.898+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:53:01.956+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:53:02.030+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:53:02.202+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:53:02.202+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:54:02.256+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:54:02.262+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:54:02.579+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:54:02.580+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:55:02.636+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:55:02.641+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:55:02.946+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:55:02.946+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:56:03.006+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:56:03.011+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:56:03.331+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:56:03.331+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:57:03.361+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:57:03.367+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:57:03.702+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:57:03.702+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:58:03.721+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:58:03.726+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:58:03.901+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:58:03.901+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T08:59:03.909+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T08:59:03.916+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T08:59:04.095+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T08:59:04.095+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:00:04.155+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:00:04.161+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:00:04.488+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:00:04.489+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:01:04.507+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:01:04.513+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:01:04.850+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:01:04.850+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:02:04.906+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:02:04.912+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:02:05.250+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:02:05.251+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:03:05.306+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:03:05.313+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:03:05.485+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:03:05.486+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:04:05.546+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:04:05.553+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:04:05.864+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:04:05.865+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:05:05.926+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:05:05.932+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:05:06.245+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:05:06.245+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:06:06.307+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:06:06.313+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:06:06.644+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:06:06.644+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:07:06.672+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:07:06.678+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:07:06.999+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:07:06.999+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:08:07.056+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:08:07.061+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:08:07.393+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:08:07.393+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:09:07.455+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:09:07.461+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:09:07.805+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:09:07.805+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:10:07.832+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:10:07.838+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:10:08.000+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:10:08.001+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:11:08.062+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:11:08.068+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:11:08.375+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:11:08.376+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:12:08.435+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:12:08.442+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:12:08.627+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:12:08.627+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:13:08.689+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:13:08.695+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:13:09.019+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:13:09.019+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:14:09.071+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:14:09.076+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:14:09.385+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:14:09.385+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:15:09.447+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:15:09.453+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:15:09.779+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:15:09.779+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:16:09.836+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:16:09.842+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:16:10.174+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:16:10.175+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:17:10.229+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:17:10.236+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:17:10.575+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:17:10.575+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:18:10.636+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:18:10.641+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:18:10.951+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:18:10.951+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:19:10.980+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:19:10.986+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:19:11.288+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:19:11.288+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:20:11.345+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:20:11.352+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:20:11.669+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:20:11.669+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:21:11.708+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:21:11.713+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:21:11.883+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:21:11.883+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:22:11.898+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:22:11.905+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:22:12.094+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:22:12.094+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:23:12.155+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:23:12.162+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:23:12.488+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:23:12.488+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:24:12.550+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:24:12.556+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:24:12.883+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:24:12.883+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:25:12.945+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:25:12.951+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:25:13.123+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:25:13.123+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:26:13.176+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:26:13.181+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:26:13.365+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:26:13.366+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:27:13.403+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:27:13.409+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:27:13.744+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:27:13.744+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:28:13.792+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:28:13.798+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:28:14.117+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:28:14.117+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:29:14.148+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:29:14.155+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:29:14.518+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:29:14.519+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:30:14.559+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:30:14.565+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:30:14.878+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:30:14.878+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:31:14.937+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:31:14.943+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:31:15.119+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:31:15.119+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:32:15.181+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:32:15.187+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:32:15.537+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:32:15.538+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:33:15.549+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:33:15.555+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:33:15.993+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:33:15.994+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:34:16.047+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:34:16.053+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:34:16.369+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:34:16.369+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:35:16.426+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:35:16.432+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:35:16.615+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:35:16.616+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:36:16.678+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:36:16.684+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:36:17.327+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:36:17.327+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:37:17.386+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:37:17.391+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:37:17.739+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:37:17.740+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:38:17.800+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:38:17.805+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:38:18.122+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:38:18.123+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:39:18.167+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:39:18.173+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:39:18.493+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:39:18.494+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:40:18.547+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:40:18.553+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:40:18.861+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:40:18.861+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:41:18.919+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:41:18.925+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:41:19.239+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:41:19.240+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:42:19.263+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:42:19.269+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:42:19.624+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:42:19.624+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:43:19.642+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:43:19.648+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:43:19.823+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:43:19.824+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:44:19.876+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:44:19.884+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:44:20.084+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:44:20.084+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:45:20.146+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:45:20.152+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:45:20.330+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:45:20.331+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:46:20.392+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:46:20.398+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:46:20.731+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:46:20.732+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:47:20.794+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:47:20.799+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:47:21.130+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:47:21.130+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:48:21.150+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:48:21.156+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:48:21.461+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:48:21.462+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:49:21.512+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:49:21.518+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:49:21.840+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:49:21.841+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:50:21.896+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:50:21.939+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:50:22.246+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:50:22.247+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:51:22.306+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:51:22.312+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:51:22.613+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:51:22.614+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:52:22.664+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:52:22.669+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:52:23.014+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:52:23.014+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:53:23.056+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:53:23.062+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:53:23.380+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:53:23.381+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:54:23.436+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:54:23.442+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:54:23.758+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:54:23.759+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:55:23.799+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:55:23.805+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:55:24.118+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:55:24.119+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:56:24.165+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:56:24.171+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:56:24.482+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:56:24.482+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:57:24.536+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:57:24.542+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:57:24.726+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:57:24.727+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:58:24.784+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:58:24.789+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:58:24.959+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:58:24.959+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T09:59:25.015+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T09:59:25.021+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T09:59:25.200+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T09:59:25.200+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:00:25.261+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:00:25.268+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:00:25.570+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:00:25.570+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:01:25.626+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:01:25.632+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:01:25.978+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:01:25.978+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:02:26.036+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:02:26.048+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:02:26.269+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:02:26.269+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:03:26.331+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:03:26.337+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:03:26.526+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:03:26.527+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:04:26.529+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:04:26.536+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:04:26.838+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:04:26.838+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:05:26.900+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:05:26.906+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:05:27.227+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:05:27.227+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:06:27.285+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:06:27.292+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:06:27.608+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:06:27.608+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:07:27.666+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:07:27.673+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:07:27.869+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:07:27.870+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:08:27.927+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:08:27.934+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:08:28.277+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:08:28.277+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:09:28.291+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:09:28.297+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:09:28.613+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:09:28.614+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:10:28.666+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:10:28.672+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:10:28.994+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:10:28.995+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:11:29.052+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:11:29.058+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:11:29.234+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:11:29.234+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:12:29.295+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:12:29.301+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:12:29.521+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:12:29.522+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:13:29.584+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:13:29.590+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:13:29.907+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:13:29.907+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:14:29.966+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:14:29.971+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:14:30.276+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:14:30.276+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:15:30.337+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:15:30.344+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:15:30.645+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:15:30.646+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:16:30.687+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:16:30.693+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:16:31.009+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:16:31.009+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:17:31.051+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:17:31.059+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:17:31.262+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:17:31.263+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:18:31.315+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:18:31.320+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:18:31.636+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:18:31.637+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:19:31.695+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:19:31.701+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:19:32.002+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:19:32.003+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:20:32.060+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:20:32.065+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:20:32.373+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:20:32.374+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:21:32.383+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:21:32.389+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:21:32.562+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:21:32.562+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:22:32.617+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:22:32.623+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:22:32.962+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:22:32.962+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:23:32.981+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:23:32.987+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:23:33.304+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:23:33.304+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:24:33.327+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:24:33.333+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:24:33.653+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:24:33.654+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:25:33.670+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:25:33.677+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:25:33.852+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:25:33.852+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:26:33.856+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:26:33.863+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:26:34.181+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:26:34.181+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:27:34.235+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:27:34.241+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:27:34.581+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:27:34.581+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:28:34.635+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:28:34.642+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:28:34.959+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:28:34.959+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:29:35.019+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:29:35.026+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:29:35.366+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:29:35.366+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:30:35.426+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:30:35.431+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:30:35.747+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:30:35.748+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:31:35.810+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:31:35.816+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:31:36.135+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:31:36.135+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:32:36.195+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:32:36.202+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:32:36.745+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:32:36.746+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:33:36.807+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:33:36.815+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:33:36.993+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:33:36.993+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:34:37.055+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:34:37.063+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:34:37.387+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:34:37.387+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:35:37.445+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:35:37.451+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:35:37.766+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:35:37.766+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:36:37.826+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:36:37.832+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:36:38.147+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:36:38.147+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:37:38.206+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:37:38.211+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:37:38.546+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:37:38.546+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:38:38.605+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:38:38.611+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:38:38.934+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:38:38.934+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:39:39.001+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:39:39.008+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:39:39.329+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:39:39.329+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:40:39.379+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:40:39.385+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:40:39.724+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:40:39.725+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:41:39.742+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:41:39.749+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:41:40.066+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:41:40.067+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:42:40.123+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:42:40.129+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:42:40.464+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:42:40.464+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:43:40.526+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:43:40.533+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:43:40.861+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:43:40.861+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:44:40.881+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:44:40.886+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:44:41.194+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:44:41.195+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:45:41.255+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:45:41.262+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:45:41.605+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:45:41.605+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:46:41.653+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:46:41.659+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:46:41.973+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:46:41.974+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:47:42.025+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:47:42.032+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:47:42.376+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:47:42.376+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:48:42.435+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:48:42.441+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:48:42.757+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:48:42.757+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:49:42.818+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:49:42.824+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:49:43.135+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:49:43.136+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:50:43.137+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:50:43.144+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:50:43.460+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:50:43.460+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:51:43.498+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:51:43.505+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:51:43.828+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:51:43.828+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:52:43.848+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:52:43.855+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:52:44.230+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:52:44.231+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:53:44.289+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:53:44.296+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:53:44.607+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:53:44.608+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:54:44.665+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:54:44.672+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:54:44.835+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:54:44.836+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:55:44.857+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:55:44.863+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:55:45.033+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:55:45.033+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:56:45.088+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:56:45.094+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:56:45.411+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:56:45.412+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:57:45.467+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:57:45.473+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:57:45.813+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:57:45.814+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:57:54.705+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T04:57:38.270656+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-02-20T10:57:54.705+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: predictit_dag.is_api_available manual__2023-02-20T04:57:38.270656+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-02-20T10:57:54.706+0000] {local_task_job.py:147} INFO - Task is not able to be run
[2023-02-20T10:58:45.856+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:58:45.862+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:58:46.183+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:58:46.184+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T10:59:46.246+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T10:59:46.252+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T10:59:46.555+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T10:59:46.556+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:00:46.615+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:00:46.621+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:00:46.928+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:00:46.929+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:01:46.964+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:01:46.970+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:01:47.278+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:01:47.279+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:02:47.340+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:02:47.419+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:02:47.750+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:02:47.751+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:03:47.805+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:03:47.811+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:03:48.136+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:03:48.137+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:04:48.183+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:04:48.190+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:04:48.351+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:04:48.351+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:05:48.413+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:05:48.419+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:05:48.743+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:05:48.744+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:06:48.796+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:06:48.806+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:06:49.149+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:06:49.149+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:07:49.208+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:07:49.214+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:07:49.536+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:07:49.537+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:08:49.595+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:08:49.602+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:08:49.926+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:08:49.927+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:09:49.985+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:09:49.991+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:09:50.299+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:09:50.300+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:10:50.332+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:10:50.338+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:10:50.640+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:10:50.640+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:11:50.702+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:11:50.708+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:11:51.033+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:11:51.034+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:12:51.091+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:12:51.096+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:12:51.428+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:12:51.428+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:13:51.480+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:13:51.486+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:13:51.683+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:13:51.683+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:14:51.729+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:14:51.735+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:14:52.048+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:14:52.049+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:15:52.109+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:15:52.114+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:15:52.420+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:15:52.420+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:16:52.467+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:16:52.473+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:16:52.779+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:16:52.780+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:17:52.840+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:17:52.845+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:17:53.189+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:17:53.189+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:18:53.246+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:18:53.253+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:18:53.563+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:18:53.563+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:19:53.605+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:19:53.611+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:19:53.924+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:19:53.924+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:20:53.950+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:20:53.956+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:20:54.284+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:20:54.285+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:21:54.346+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:21:54.351+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:21:54.672+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:21:54.672+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:22:54.710+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:22:54.716+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:22:54.917+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:22:54.917+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:23:54.975+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:23:54.981+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:23:55.294+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:23:55.294+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:24:55.345+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:24:55.350+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:24:55.522+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:24:55.522+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:25:55.575+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:25:55.582+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:25:55.887+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:25:55.887+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:26:55.891+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:26:55.896+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:26:56.211+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:26:56.211+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:27:56.271+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:27:56.276+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:27:56.619+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:27:56.620+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:28:56.649+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:28:56.654+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:28:56.962+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:28:56.962+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
[2023-02-20T11:29:57.015+0000] {http.py:122} INFO - Poking: api/
[2023-02-20T11:29:57.021+0000] {base.py:73} INFO - Using connection ID 'predictit_api' for task execution.
[2023-02-20T11:29:57.338+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-02-20T11:29:57.338+0000] {http.py:164} ERROR - {
  "message": "No HTTP resource was found that matches the request URI 'https://www.predictit.org/api/marketdata/api/'."
}
